Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -160,12 +160,17 @@ jobs:
       - name: Copy containerd log from container
         if: ${{ failure() }}
         run: |
-          CONTAINER_ID=$(docker ps -qf "name=rancher" | head -n1)
-          if [ -n "$CONTAINER_ID" ]; then
-            docker cp "$CONTAINER_ID:/var/lib/rancher/k3s/agent/containerd/containerd.log" containerd.log || echo "Failed to copy containerd.log"
-          else
-            echo "Rancher container not found"
-          fi          
+          docker cp cypress:/var/lib/rancher/k3s/agent/containerd/containerd.log containerd.log || echo "Failed to copy containerd.log"
+
+      - name: Upload containerd.log
+        uses: actions/upload-artifact@v4
+        if: ${{ failure() }}
+        with:
+          name: ${{github.run_number}}-${{github.run_attempt}}-containerd-log-${{ matrix.role.tag }}${{ matrix.features[0] }}${{ matrix.features[1] }}
+          path: containerd.log
+          if-no-files-found: warn
+          retention-days: 5
+          compression-level: 9          
 
   a11y-test:
     if: "!contains( github.event.pull_request.labels.*.name, 'ci/skip-e2e')"
