wip

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -35,7 +35,8 @@ env:
 jobs:
   e2e-ui-build:
     if: "!contains( github.event.pull_request.labels.*.name, 'ci/skip-e2e')"
-    runs-on: ubuntu-latest
+    container: ubuntu-latest
+    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
     steps:
       - uses: actions/checkout@v4
         with:
@@ -61,86 +62,85 @@ jobs:
           retention-days: 10
           compression-level: 9
 
+  # e2e-test:
+  #   if: "!contains( github.event.pull_request.labels.*.name, 'ci/skip-e2e')"
+  #   needs: e2e-ui-build
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       role: [
+  #         { username: 'admin', tag: '@adminUser' }, 
+  #         { username: 'standard_user', tag: '@standardUser' }
+  #       ]
+  #       features:  [
+  #         ['@navigation', '@extensions'],
+  #         ['@charts'],
+  #         ['@explorer'],
+  #         ['@fleet'],
+  #         ['@generic', '@globalSettings'],
+  #         ['@manager'],
+  #         ['@userMenu', '@usersAndAuths'],
+  #         ['@components'],
+  #         ['@vai']
+  #       ]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 1
+  #     - name: Setup env
+  #       uses: ./.github/actions/setup
 
-  e2e-test:
-    if: "!contains( github.event.pull_request.labels.*.name, 'ci/skip-e2e')"
-    needs: e2e-ui-build
-    strategy:
-      fail-fast: false
-      matrix:
-        role: [
-          { username: 'admin', tag: '@adminUser' }, 
-          { username: 'standard_user', tag: '@standardUser' }
-        ]
-        features:  [
-          ['@navigation', '@extensions'],
-          ['@charts'],
-          ['@explorer'],
-          ['@fleet'],
-          ['@generic', '@globalSettings'],
-          ['@manager'],
-          ['@userMenu', '@usersAndAuths'],
-          ['@components'],
-          ['@vai']
-        ]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 1
-      - name: Setup env
-        uses: ./.github/actions/setup
+  #     # Installing fixed version of Chrome since latest version does not work (117-118 didn't work)
+  #     # Leaving this here again in case we need to pin to a specific Chrome version in the future
+  #     # - name: Install Chrome 116
+  #     #   run: |
+  #     #     sudo apt-get install -y wget
+  #     #     cd /tmp
+  #     #     wget -q http://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_116.0.5845.187-1_amd64.deb
+  #     #     sudo apt-get install -y --allow-downgrades ./google-chrome-stable_116.0.5845.187-1_amd64.deb
+  #     #     google-chrome --version
 
-      # Installing fixed version of Chrome since latest version does not work (117-118 didn't work)
-      # Leaving this here again in case we need to pin to a specific Chrome version in the future
-      # - name: Install Chrome 116
-      #   run: |
-      #     sudo apt-get install -y wget
-      #     cd /tmp
-      #     wget -q http://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_116.0.5845.187-1_amd64.deb
-      #     sudo apt-get install -y --allow-downgrades ./google-chrome-stable_116.0.5845.187-1_amd64.deb
-      #     google-chrome --version
-
-      - name: Download e2e build
-        uses:  actions/download-artifact@v4
-        with:
-         name: ${{ env.E2E_BUILD_DIST_NAME }}
-         path: ${{ env.E2E_BUILD_DIST_DIR }}
-      - name: Download e2e build ember
-        uses:  actions/download-artifact@v4
-        with:
-         name: ${{ env.E2E_BUILD_DIST_EMBER_NAME }}
-         path: ${{ env.E2E_BUILD_DIST_EMBER_DIR }}
+  #     - name: Download e2e build
+  #       uses:  actions/download-artifact@v4
+  #       with:
+  #        name: ${{ env.E2E_BUILD_DIST_NAME }}
+  #        path: ${{ env.E2E_BUILD_DIST_DIR }}
+  #     - name: Download e2e build ember
+  #       uses:  actions/download-artifact@v4
+  #       with:
+  #        name: ${{ env.E2E_BUILD_DIST_EMBER_NAME }}
+  #        path: ${{ env.E2E_BUILD_DIST_EMBER_DIR }}
       
-      - name: Run Rancher
-        run: yarn e2e:docker
+  #     - name: Run Rancher
+  #       run: yarn e2e:docker
       
-      - name: Setup Rancher and user
-        run: |
-          yarn e2e:prod
-        env: 
-          GREP_TAGS: ${{ matrix.role.tag }}Setup+${{ matrix.features[0] }} --@jenkins ${{ matrix.role.tag }}Setup+${{ matrix.features[1] || matrix.features[0] }} --@jenkins
-          TEST_USERNAME: admin
-          TEST_ONLY: setup
-      - name: Run user tests
-        run: |
-          yarn e2e:prod
-          [ "$BUILD_DASHBOARD" != "false" ] || exit 0
-        env: 
-          TEST_SKIP: setup
-          GREP_TAGS: ${{ matrix.role.tag }}+${{ matrix.features[0] }} --@jenkins ${{ matrix.role.tag }}+${{ matrix.features[1] || matrix.features[0] }} --@jenkins
-          TEST_USERNAME: ${{ matrix.role.username }}
+  #     - name: Setup Rancher and user
+  #       run: |
+  #         yarn e2e:prod
+  #       env: 
+  #         GREP_TAGS: ${{ matrix.role.tag }}Setup+${{ matrix.features[0] }} --@jenkins ${{ matrix.role.tag }}Setup+${{ matrix.features[1] || matrix.features[0] }} --@jenkins
+  #         TEST_USERNAME: admin
+  #         TEST_ONLY: setup
+  #     - name: Run user tests
+  #       run: |
+  #         yarn e2e:prod
+  #         [ "$BUILD_DASHBOARD" != "false" ] || exit 0
+  #       env: 
+  #         TEST_SKIP: setup
+  #         GREP_TAGS: ${{ matrix.role.tag }}+${{ matrix.features[0] }} --@jenkins ${{ matrix.role.tag }}+${{ matrix.features[1] || matrix.features[0] }} --@jenkins
+  #         TEST_USERNAME: ${{ matrix.role.username }}
           
-      - name: Upload screenshots
-        uses: actions/upload-artifact@v4
-        if: ${{ failure() }}
-        with:
-          name: ${{github.run_number}}-${{github.run_attempt}}-screenshots-${{ matrix.role.tag }}+${{ matrix.features[0] }}
-          path: cypress/screenshots
-
+  #     - name: Upload screenshots
+  #       uses: actions/upload-artifact@v4
+  #       if: ${{ failure() }}
+  #       with:
+  #         name: ${{github.run_number}}-${{github.run_attempt}}-screenshots-${{ matrix.role.tag }}+${{ matrix.features[0] }}
+  #         path: cypress/screenshots
 
   unit-test:
-    runs-on: ubuntu-latest
+    container: ubuntu-latest
+    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
     steps:
       - uses: actions/checkout@v4
         with:
@@ -161,9 +161,9 @@ jobs:
           name: ${{github.run_number}}-${{github.run_attempt}}-coverage
           path: coverage-artifacts/**/*
 
-
   i18n:
-    runs-on: ubuntu-latest
+    container: ubuntu-latest
+    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
     steps:
       - uses: actions/checkout@v4
         with:
@@ -172,9 +172,9 @@ jobs:
       - name: Run i18n lint
         uses: ./.github/actions/i18n-lint
 
-
   lint:
-    runs-on: ubuntu-latest
+    container: ubuntu-latest
+    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
     steps:
       - uses: actions/checkout@v4
         with:
@@ -183,9 +183,9 @@ jobs:
       - name: Run tests
         uses: ./.github/actions/lint
       
-
   check-i18n:
-    runs-on: ubuntu-latest
+    container: ubuntu-latest
+    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
     steps:
       - uses: actions/checkout@v4
         with:
@@ -202,40 +202,39 @@ jobs:
           # Falure won't fail the job (remove -x when all current issues are fixed)
           ./scripts/check-i18n -s -x
 
+  # # coverage:
+  # #   runs-on: ubuntu-latest
+  # #   needs:
+  # #     - unit-test
+  # #   steps:
+  # #     - uses: actions/checkout@v3
+  # #       with:
+  # #         fetch-depth: 1
 
-  # coverage:
+  # #     - uses: actions/setup-node@v4
+  # #       with:
+  # #         node-version-file: '.nvmrc'
+
+  # #     - name: Download Coverage Artifacts
+  # #       uses: actions/download-artifact@v3
+  # #       with:
+  # #         name: ${{github.run_number}}-${{github.run_attempt}}-coverage
+
+  # #     - name: Install Codecov CLI
+  # #       run : .github/workflows/scripts/install-codecov.sh
+
+  # #     - name: Upload tests coverage report to Codecov
+  # #       run: ./codecov --verbose upload-process -t ${{ secrets.CODECOV_TOKEN }} -n ${{github.run_number}}-${{github.run_attempt}}-coverage -F unit -f ./coverage/coverage-unit.json
+
+  # check-e2e-tags:
   #   runs-on: ubuntu-latest
-  #   needs:
-  #     - unit-test
   #   steps:
-  #     - uses: actions/checkout@v3
+  #     - uses: actions/checkout@v4
   #       with:
   #         fetch-depth: 1
-
   #     - uses: actions/setup-node@v4
   #       with:
   #         node-version-file: '.nvmrc'
-
-  #     - name: Download Coverage Artifacts
-  #       uses: actions/download-artifact@v3
-  #       with:
-  #         name: ${{github.run_number}}-${{github.run_attempt}}-coverage
-
-  #     - name: Install Codecov CLI
-  #       run : .github/workflows/scripts/install-codecov.sh
-
-  #     - name: Upload tests coverage report to Codecov
-  #       run: ./codecov --verbose upload-process -t ${{ secrets.CODECOV_TOKEN }} -n ${{github.run_number}}-${{github.run_attempt}}-coverage -F unit -f ./coverage/coverage-unit.json
-
-  check-e2e-tags:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 1
-      - uses: actions/setup-node@v4
-        with:
-          node-version-file: '.nvmrc'
-      - name: Check e2e tags
-        run: |
-          ./scripts/check-e2e-tests-for-tags
+  #     - name: Check e2e tags
+  #       run: |
+  #         ./scripts/check-e2e-tests-for-tags
